### ISSUE TITLE
Implement network related endpoints for JSON-RPC EVM endpoint

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-evm-gateway#1]
A core requirement for Flow EVM is to provide a publicly accessible JSON-RPC endpoint which conforms to the formal [Ethereum RPC spec](https://ethereum.github.io/execution-apis/api-documentation/). We are breaking the full surface area of the API across different issues. This issue focuses on the most basic required endpoint for all other functionality, the network related functions.

## Instructions

For the following endpoints: 

* `eth_chainId // returns the chainID` 
* `eth_blockNumber // returns the latest block number` 
* `eth_syncing // return false for now`

We will need to:

* Understand the internal wiring to be implemented and what interactions with BridgedAccount or other Flow constructs this will have in the functions implementation. Formalize the specification/requirements through discussion in this issue
* Implement the endpoints above including corresponding automated tests to the agreed upon spec

**Comment by m-Peter** [comment]
Mapping some methods to the current Access API:
1. `eth_chainId` -> https://developers.flow.com/references/run-and-secure/nodes/access-api#network-parameters
2. `eth_blockNumber` -> https://developers.flow.com/references/run-and-secure/nodes/access-api#getlatestblock
3. `eth_syncing` -> This has no equivalent in the Access API

Regarding method #2, I guess we only care about **sealed** blocks.
