### ISSUE TITLE
Validation of transactions submitted

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-evm-gateway#117]
Right now EVM gateway will forward transaction no matter the contents and rely on EVM Core to validate it and process it. We should validate the transactions in EVM gateway to prevent invalid transactions being forwarded but also to do further validation based on configuration. 
Some rules should be implemented:
- Check that the transaction submitted doesn't have gas price set that is lower than the minimum accepted by EVM GW config
(think about other validation rules, reference go-eth implementation).

**Comment by m-Peter** [comment]
- Another validation we should add is the gas limit isn't beyond the maximum allowed.

**Comment by m-Peter** [comment]
The transaction validation logic from Geth: https://github.com/ethereum/go-ethereum/blob/master/core/txpool/validation.go#L202
