### ISSUE TITLE
Improve key-rotation mechanism

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-evm-gateway#118]
If there is a bigger load on transaction submission it might come to a case where there are less keys than transactions being submitted which might mean that the same key will be used before the previous transaction is sealed. 
Improvement should be made to wait for that transaction to be sealed before submitting a new one. There's also a possibility with offline nonce tracking with a frequent sync.

**Comment by m-Peter** [comment]
Related to https://github.com/onflow/flow-evm-gateway/issues/477

**Comment by j1010001** [comment]
instead of sealed we could use just Tx executed
