### ISSUE TITLE
Transactions should be optimized

### ISSUE THREAD

**Issue by turbolent** [onflow/flow-evm-gateway#123]
### Issue To Be Solved

EVM transactions are currently submitted by wrapping them in a Cadence transaction.

The Cadence transaction sends the EVM transaction as a `[UInt8]` value, see https://github.com/onflow/flow-evm-gateway/blob/816b5b780c39be7e7ad6f46a4cf37f216f79750a/services/requester/cadence/run.cdc#L3

The current encoding of such values in the current format, JSON, is very inefficient.

### Suggest A Solution

Until we add support for the new, more efficient, Cadence value encoding format, CCF, it might be best to send the EVM transaction in a more efficient manner. For example, it could be sent as a hex-encoded string, then decoded in the transaction.

**Comment by m-Peter** [comment]
That's a good point :+1: Thanks for the report :pray: 
The change is rather straightforward to do, and in fact it might be easier to construct a `cadence.String` from the `[]byte` data containing the RLP-encoded tx (see https://github.com/onflow/flow-evm-gateway/blob/main/services/requester/requester.go#L162)

**Comment by turbolent** [comment]
Note that Cadence `String`s are required to be valid UTF-8, so it's not possible to use them for arbitrary byte arrays.

**Comment by m-Peter** [comment]
The byte array will first pass through `hex.EncodeToString(data)` (where `data` is the byte array), and that string will be used to construct a value of `cadence.String`.
