### ISSUE TITLE
Implementing metrics

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-evm-gateway#125]
We need comprehensive metrics to measure the performance and resource usage of our APIs. This will help us understand the performance of different API methods and track various states and errors.

```[tasklist]
### Performance
- [x] Measure end-to-end request/response time by method call (track the time taken from the start of a request to the return of the response for each method call to understand relative performance and user experience using percentiles).
- [ ] Monitor time it takes for Flow transaction to be submitted and a result is returned, with the transaction status
- [x] API requests per time interval metric
- [x] API calls by API endpoint (most used to least used calls)
```

Measuring performance can/should be done using tracing, so we can have multiple sub-calls measured as well. Ideally, we should have all the network calls as a sub-trace as well as any APIs. Traces should be enabled with a flag and not on by default. 
Each API response time should also submit a simple metric measuring the time it took for the request to be processed. 

Be careful to also include websocket request/responses metrics. 

```[tasklist]
## State
- [x] Ingestion index health is a boolean value that is being set to false if the latest indexed EVM height falls behind the latest EVM height by X
- [x] Execution EVM traces index health is a boolean value that should be set to false if there are any traces that failed to download
- [x] API errors should be submitted to a counter metric
- [ ] Report fees paid on Flow and EVM side as a metric
- [x] Metric for users EVM contract addresses which are being called
- [x] Database size (folder size)
```

```[tasklist]
## Ingestion
- [x] EVM height should be submitted as a value on event ingestion
- [x] Trace download failures should be recorded
```

We should use prometheus and open telemetry to collect the traces and metrics.

**Comment by m-Peter** [comment]
For JSON-RPC endpoints that are served over `WebSocket`, such as subscriptions and filtering of entities, we should add some dedicated metrics as well, e.g. active connections etc.

**Comment by m-Peter** [comment]
- https://github.com/onflow/flow-evm-gateway/blob/main/services/ingestion/engine.go#L123 logs plenty but the event count is always 0. Not sure how useful this is unless we can improve it (or unless we're just not yet using it fully)
 - https://github.com/onflow/flow-evm-gateway/blob/main/api/api.go#L296 - see this relatively regularly, so i guess we should implement the TODO
 - One (or all) of the following log lines in requester.go which log the data payload is logging data payload size that exceeds grafana max log line size. https://github.com/onflow/flow-evm-gateway/blob/main/services/requester/requester.go#L144 The data logged anyway is just hex. If we don't need to see the payload during debugging, probably makes more sense to just log the data size (and we should maybe log that to info level)

**Comment by sideninja** [comment]
> https://github.com/onflow/flow-evm-gateway/blob/main/services/ingestion/engine.go#L123 logs plenty but the event count is always 0. Not sure how useful this is unless we can improve it (or unless we're just not yet using it fully)

Why do you say it's always 0? It should not be 0 when there are EVM events included right? but it is the case a lot of times it is 0 because there are just new blocks and we get heartbeat interval with 0 events. I think that's a good debug log so we can see the engine is progressing even though no evm events are emitted, but we still see the cadence height being incremented.

**Comment by sideninja** [comment]
> https://github.com/onflow/flow-evm-gateway/blob/main/api/api.go#L296 - see this relatively regularly, so i guess we should implement the TODO

I agree, it can be changed to todo.

**Comment by sideninja** [comment]
> One (or all) of the following log lines in requester.go which log the data payload is logging data payload size that exceeds grafana max log line size. https://github.com/onflow/flow-evm-gateway/blob/main/services/requester/requester.go#L144 The data logged anyway is just hex. If we don't need to see the payload during debugging, probably makes more sense to just log the data size (and we should maybe log that to info level)

My argument is that on deployment to production we shouldn't have debug level of logs. But running locally and on testnet for now it is useful to have verbose logs. This log to me is useful because sometimes I decode the transaction to make sure if the correct data was sent and to see if there was an error in the transaction itself. 

Generally I would say debug logs can be very verbose, that is the purpose, to see more when you want to debug. So I think we could even add more to debug log in future. If there is a limitation to grafana then that's a bummer, but again I don't think we should have this on grafana unless it's a previewnet deployment in which case its ok I guess even if limit is reached.

**Comment by sideninja** [comment]
Add metrics for index health. Trace index health is dependent on the trace download success, if one is failed the index becomes unhealthy. Transaction index health is dependent on how far back the latest ingested event is from the latest height on the network. If too far behind the index is unhealthy.

**Comment by sideninja** [comment]
Another high priority metric is: https://github.com/onflow/flow-evm-gateway/issues/384

**Comment by j1010001** [comment]
First set of metrics is implemented and Grafana Dashboard created: https://flowfoundation.grafana.net/d/PkvVJj4Mz/mainnet-general?from=now-24h&to=now&timezone=America%2FVancouver
