### ISSUE TITLE
Launch readiness tasks 

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-evm-gateway#13]
# Issue To Be Solved

A number of items need to be addressed to prepare JSON-RPC for launch. The assumption is that all but the last item would be handled by this issue.  

```[tasklist]
## Tasks
- [ ] Logging
- [ ] Alerting
- [ ] Monitoring
- [ ] End-to-end tests
- [ ] Benchmarking
- [x] Expose gateway through emulator (to be tracked in Emulator repo)
```

**Comment by sideninja** [comment]
close in favour https://github.com/onflow/flow-evm-gateway/issues/126
