### ISSUE TITLE
Missing Block Fields

### ISSUE THREAD

**Issue by jribbink** [onflow/flow-evm-gateway#145]
### Problem

I apologize in advance if this issue is already on the radar/tracked somewhere, but I couldn't find it.

This is tangential to the issue submitted yesterday #137.  The fields returned from the `eth_getBlockByHash` & `eth_getBlockByNumber` responses are somewhat limited & are not satisfactory for some clients.

There are a number of fields missing from [the spec](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getblockbyhash), but in particular, `ethers` will fail unless the following fields are added to the response:

 - `timestamp`
 - `difficulty`
 - `gasLimit`
 - `gasUsed`
 - `extraData`

I think this is probably because these values are parsed by `ethers`, so undefined throws off the library (and others missing fields are not parsed, so they don't cause any immediate issues when making this query).  The availability of these fields would fix `ethers.getBlock` calls, but I am unsure if any other incorrect/missing fields I didn't mention will still cause issues with other parts of the `ethers` API.

In general, I think it would be ideal if the `Block` model were at least populated with empty values (if it is not easy/possible to provide a value for these missing fields) so that clients can still parse this data without throwing errors.

### Steps to Reproduce 

```js
const { ethers } = require('ethers')
const provider = new ethers.JsonRpcProvider('https://previewnet.evm.nodes.onflow.org')
provider.getBlock("latest").then(console.log)
```

(note: you will have to be using the current `flow-evm-gateway`, not the live, deployed one because you will end up seeing #137 instead)

### Acceptance Criteria

Minimum, these fields listed exist in some capacity.  But it is probably ideal to at least provided empty values for other fields, as mentioned, to protect against future issues.
  
### Context

Blocking integration with clients/writing docs.

**Comment by sideninja** [comment]
@jribbink great call out

**Comment by ianthpun** [comment]
@sideninja I noticed this was merged 4 days ago, are we able to deploy this? There seems to be a bug related to hardhats ignition deployer that this might solve 👍  thanks!

**Comment by sideninja** [comment]
@ianthpun yes we did deploy today. Sorry was busy with some other stuff.

**Comment by sideninja** [comment]
@ianthpun let me know if it fixes it. cc @m-Peter

**Comment by nvdtf** [comment]
Can confirm this fixed `forge create` for me to deploy contracts to Previewnet

**Comment by sideninja** [comment]
Will close, feel free to reopen if something new is discovered

**Comment by ianthpun** [comment]
damn, wish I could say the same

![image](https://github.com/onflow/flow-evm-gateway/assets/6364887/a81bb2ff-8039-495b-8b74-9471a63d89d3)

let me get to the bottom of what the error is before i reopen this

**Comment by sideninja** [comment]
I will loop @m-Peter into this. Report back when you find anything @ianthpun

**Comment by m-Peter** [comment]
@sideninja I have got this working, see [comment](https://github.com/NomicFoundation/hardhat-ignition/issues/738#issuecomment-2117419330). This is not related to any missing block fields, but a condition on confirmations that hardhat ignition performs. So I am going to close this.
