### ISSUE TITLE
Implement API functionality to support transactions

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-evm-gateway#2]
A core requirement for Flow EVM is to provide a publicly accessible JSON-RPC endpoint which conforms to the formal [Ethereum RPC spec](https://ethereum.github.io/execution-apis/api-documentation/). We are breaking the full surface area of the API across different issues. This issue focuses on the second most basic required endpoint for all other functionality, functionality to execute transactions.

## Instructions

For the following endpoints: 

* eth_sendRawTransaction
* eth_call
* eth_createAccessList 
* eth_feeHistory // transaction fee history 
* eth_gasPrice // returns the gas price 
* eth_maxPriorityFeePerGas 

We will need to:

* Understand the internal wiring to be implemented and what interactions with BridgedAccount or other Flow constructs this will have in the functions implementation. Formalize the specification/requirements through discussion in this issue
* Implement the endpoints above including corresponding automated tests to the agreed upon spec

**Comment by m-Peter** [comment]
Besides `eth_sendRawTransaction` I also see `eth_sendTransaction` which _signs and submits a transaction_, according to the Ethereum RPC spec. This would most likely correspond to https://developers.flow.com/references/run-and-secure/nodes/access-api#sendtransaction in Access API.

We might also want to support `eth_getTransactionByHash` which _returns the information about a transaction requested by transaction hash_, according to the Ethereum RPC spec. This would most likely correspond to https://developers.flow.com/references/run-and-secure/nodes/access-api#gettransaction in Access API.
