### ISSUE TITLE
Supporting `forge script` for Foundry tools

### ISSUE THREAD

**Issue by nvdtf** [onflow/flow-evm-gateway#247]
## Instructions

Foundry is a popular EVM toolchain. We've received reports from partners having trouble using it with Flow PreviewNet, specifically the `script` feature to manage deployments and updates.

A similar problem has been observed with HardHat Ignition (https://github.com/NomicFoundation/hardhat-ignition/issues/738).

### Problem

Foundry can deploy contracts normally using `forge create` but deployments with `forge script` error. The error we see is:
```
failed to get account for 0x0514250500425DdE3bb35D49cC75F5ea861BCbFc: server returned an error response: error code -32000: internal error address=0x0514250500425DdE3bb35D49cC75F5ea861BCbFc
```

This error does not happen continuously. There are periods of time where the script runs and succeeds but mostly it fails with the above error. We couldn't find a specific pattern to succeed/fail.

### Steps to Reproduce 

Here's a quick way to reproduce this error:

1. Init a new project:

   ```shell
   forge init
   ```

2. Create new key pair and fund with faucet:

   ```shell
   cast wallet new
   ```

3. Normal deployment succeeds with starter template contract:

   ```shell
   forge create --rpc-url https://previewnet.evm.nodes.onflow.org \
    --private-key $YOUR_PRIVATE_KEY \
    --legacy \
    src/Counter.sol:Counter
   ```

4. Update `script/Counter.s.sol`:

   ```solidity
   // SPDX-License-Identifier: UNLICENSED
   pragma solidity ^0.8.13;
   
   import {Script, console} from "forge-std/Script.sol";
   import "../src/Counter.sol";
   
   contract CounterScript is Script {
       function setUp() public {}
   
       function run() public {
           // Setup
           uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
           vm.startBroadcast(deployerPrivateKey);
   
           // Deploy
           new Counter();
   
           // End
           vm.stopBroadcast();
       }
   }
   ```

4. Run script (will fail):

   ```shell
   export PRIVATE_KEY=0xPRIVATE_KEY
   
   forge script script/Counter.s.sol:CounterScript \
    --broadcast \
    -vvv \
    --legacy \
    --rpc-url https://previewnet.evm.nodes.onflow.org/
   ```

### Acceptance Criteria

`forge script` should function properly as `forge create`.
  
### Context

This is blocking to USDC EVM development as they are relying on deployment scripts. You can check out sample Circle scripts [here](https://github.com/circlefin/stablecoin-evm/tree/master/scripts/deploy) but the simple case outlined above will also reproduce the error.

**Comment by m-Peter** [comment]
I had a shot at this locally and on PreviewNet, but I can't seem to reproduce any failures. Here's what I got:

```bash
cast wallet new
Successfully created new keypair.
Address:     0xd6AACF6C06908dd6CB525bd7d999A7C9F36c6AaE
Private key: 0x32589b2b129a420489a109929f5aa82a3e6ff116303972c4e0fb3e9163d9edd5
```

```bash
forge create --rpc-url https://previewnet.evm.nodes.onflow.org \  
 --private-key 0x32589b2b129a420489a109929f5aa82a3e6ff116303972c4e0fb3e9163d9edd5 \
 --legacy \
 src/Counter.sol:Counter
[⠊] Compiling...
No files changed, compilation skipped
Deployer: 0xd6AACF6C06908dd6CB525bd7d999A7C9F36c6AaE
Deployed to: 0x50aC67b41B4610657F895f2f80a3Fc2816ca172C
Transaction hash: 0x13d699907209491f85f5858337cfb6f29918560bcf4c362239e68b34c1b528e6
```

```bash
export PRIVATE_KEY=0x32589b2b129a420489a109929f5aa82a3e6ff116303972c4e0fb3e9163d9edd5

forge script script/Counter.s.sol:CounterScript \
 --broadcast \
 -vvv \
 --legacy \
 --rpc-url https://previewnet.evm.nodes.onflow.org/
[⠒] Compiling...
No files changed, compilation skipped
Script ran successfully.

## Setting up 1 EVM.

==========================

Chain 646

Estimated gas price: 0 gwei

Estimated total gas used for script: 138729

Estimated amount required: 0. ETH

==========================
##
Sending transactions [0 - 0].
⠁ [00:00:00] [###########################################################################################] 1/1 txes (0.0s)##
Waiting for receipts.
⠉ [00:00:07] [#######################################################################################] 1/1 receipts (0.0s)
##### 646
✅  [Success]Hash: 0xb92434f0e232993b091c9a6a819a593e0e908f72fc79012ef8ce800ef268944c
Contract Address: 0x9d533aeD3486648B2A94e73899CA57D82E3856b3
Block: 5988
Gas Used: 106733



==========================

ONCHAIN EXECUTION COMPLETE & SUCCESSFUL.
Total Paid: 0. ETH (106733 gas * avg 0 gwei)

Transactions saved to: /home/mpeter/Dev/forge-testing/broadcast/Counter.s.sol/646/run-latest.json

Sensitive values saved to: /home/mpeter/Dev/forge-testing/cache/Counter.s.sol/646/run-latest.json
```

@nvdtf Can you have another attempt on this, and let me know?

**Comment by nvdtf** [comment]
I just recreated and tried again and got success like you. 

Can't produce a failure right now, but this was the behaviour when I reported this issue. I need to find what triggers failures and if it's happening still or not.

Will report back to Circle to test. Will keep this issue open in case we find out more.

**Comment by nvdtf** [comment]
Getting errors now, can't produce a success case:
```
→ forge script script/Counter.s.sol:CounterScript \
    --broadcast \
    --private-key 0x32589b2b129a420489a109929f5aa82a3e6ff116303972c4e0fb3e9163d9edd5 \
    -vvv \
    --legacy \
    --rpc-url https://previewnet.evm.nodes.onflow.org/
[⠊] Compiling...
No files changed, compilation skipped
2024-05-17T18:19:49.318743Z ERROR sharedbackend: Failed to send/recv `basic` err=failed to get account for 0xd6AACF6C06908dd6CB525bd7d999A7C9F36c6AaE: server returned an error response: error code -32000: internal error address=0xd6AACF6C06908dd6CB525bd7d999A7C9F36c6AaE
Error:
failed to get account for 0xd6AACF6C06908dd6CB525bd7d999A7C9F36c6AaE: server returned an error response: error code -32000: internal error
```
Could Foundry be querying accounts for nonces and can't fetch them?

**Comment by franklywatson** [comment]
@sideninja for visibility

**Comment by nvdtf** [comment]
I found a way to make the failure go away:
* Trying the above `script` after waiting for a while produces a failure.
* Generate an unrelated wallet (`cast wallet new`) and fund it with the PreviewNet faucet.
* Retry step 1. It now succeeds. It will continue to succeed for some time.
  * Note that the account we're using is NOT the account we just generated. It's the same script as step 1 with same key.
 
This makes me think this might be related to block production on PreviewNet and what tools expect.

**Comment by m-Peter** [comment]
@nvdtf Thanks for the detailed breakdown.

> This makes me think this might be related to block production on PreviewNet and what tools expect. Using the faucet produces a new block. Maybe if the latest block is stale, the tool can't query something it needs like a nonce?

Regarding the above, this looks similar to the issue I discovered here: https://github.com/NomicFoundation/hardhat-ignition/issues/738#issuecomment-2117419330. Where the command hangs until the necessary blocks for tx confirmation are produced.

**Comment by m-Peter** [comment]
> Context
> 
> This is blocking to USDC EVM development as they are relying on deployment scripts. You can check out sample Circle scripts [here](https://github.com/circlefin/stablecoin-evm/tree/master/scripts/deploy) but the simple case outlined above will also reproduce the error.

@nvdtf Regarding the block of USDC EVM deployment, I think this [comment](https://github.com/onflow/flow-evm-gateway/issues/273#issuecomment-2139136720), solves the error you faced.

As for the current issue, I am not able to re-produce a failure, neither locally nor in PreviewNet.

> This makes me think this might be related to block production on PreviewNet and what tools expect. Using the faucet produces a new block. Maybe if the latest block is stale, the tool can't query something it needs like a nonce?

I found out that hardhat-ignition plugin makes use of confirmations, which is basically related to block production. But there's a setting to override this.

I am closing the issue for now. Feel free to re-open, if you find something strange :pray:
