### ISSUE TITLE
Implement the missing `debug_traceTransaction` method.

### ISSUE THREAD

**Issue by btspoony** [onflow/flow-evm-gateway#251]
## Issue To Be Solved

Missing `debug_traceTransaction` method in the gateway endpoint.
It returns the transaction execution details as a Call object (the following schema):
```
{
   "from":"EVM Address",
   "gas":"Hex UInt256",
   "gasUsed":"Hex UInt256",
   "to":"EVM Address",
   "input":"Hex String",
   "output":"Hex String",
   "calls":[] // The children Call objects, recursive records of all cross-contract calls objects occurred in the method.
   "value": "Hex UInt256",
    "type":"CALL or DELEGATECALL or STATICCALL" 
}
```
for the `type` field, only three available:
- CALL -> modify the storage of the target contract
- DELEGATECALL -> modify the storage of the current contract
- STATICCALL -> do not make any modifications in a pure view call.

for the `value` field, refers to the transferred Native Token.

---

The main usage scenarios of this interface:
1. Native Token transfers tracking:
   - Because in EVM, the transfer of Native Token cannot be determined through tracking Transfer events like ERC20.
   -  If the client needs to know exactly what changes have occurred to the Native Token in a transaction, it must be determined through tracing the actual execution details of the transaction.
2. Internal Transaction Status
   - Usually the blockchain browser or data analytics team needs to present and obtain all the business details of a transaction.

## Suggest A Solution

Implement this API method.
  
## Context

Discord: https://discord.com/channels/613813861610684416/1167476806333513800/1240313449112932485
References from the conversation:
-  https://docs.blockscout.com/for-developers/information-and-settings/requirements/node-tracing-json-rpc-requirements 
-  https://docs.alchemy.com/reference/debug-tracetransaction#calltracer
- https://github.com/blockscout/blockscout-rs/blob/15dead596e20afe54ad97f86940901596f2576e1/user-ops-indexer/user-ops-indexer-logic/src/indexer/rpc_utils.rs#L145
-  https://gist.github.com/franklywatson/cf3e3a780888aa306a379e0f95b40f33

**Comment by sideninja** [comment]
Thank you @btspoony for nice breakdown. We should discuss this further once the priority tasks are done. 
cc @j1010001 @franklywatson

**Comment by franklywatson** [comment]
Based on a discussion with another key analytics partner we will likely need to consider adding support for both `debug_traceTransaction()` and `debug_traceByBlockNumber()` or the following pair `trace_transaction()` & `trace_block()`. cc @sideninja @j1010001 @ramtinms 

![Screenshot 2024-05-16 at 8 11 56 AM](https://github.com/onflow/flow-evm-gateway/assets/128842/c4c1417b-9c7b-477e-9ac9-7952fbf26a79)

**Comment by franklywatson** [comment]
Does this also implement debug_traceBlockByNumber() as indicated in previously [shared](https://github.com/onflow/flow-evm-gateway/issues/251#issuecomment-2115540588) screen shot?

**Comment by m-Peter** [comment]
@franklywatson The `debug_traceBlockByNumber()` is basically an aggregation of `debug_traceTransaction()` for a given block. Most Flow EVM blocks have 1 transaction, but with the introduction of `EVM.batchRun` there could be more than one.
Although the `debug_traceBlockByNumber()` is not yet implemented, the underlying traces are indexed, so I am assuming it is not much work to get it done. I'll need to double check though
