### ISSUE TITLE
Improve handling of pending transactions

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-evm-gateway#264]
We should improve the handling of transaction submissions, more specifically there should be a process that tracks transaction requests for submission and while the transaction is pending on the network it should keep checking the status. This process should also be treated as the transaction pool which should be reported back to the APIs.

Right now transactions are submitted after received and then the result is ingested once the transaction event is emitted. This creates a period when a transaction is submitted but the transaction event is not yet emitted and the user doesn't know what is going on with the transaction. 

We should define what happens when a Flow transaction fails (not the EVM), and what would be appropriate response for the API. We should also think about whether we need to check the transaction status and do an action if it's successful, or just showing the transaction during this period as pending.

**Comment by franklywatson** [comment]
Possibly related to #273

**Comment by sideninja** [comment]
Implemented by #299
