### ISSUE TITLE
Add CI workflow to verify changes against a live network

### ISSUE THREAD

**Issue by m-Peter** [onflow/flow-evm-gateway#348]
It would be useful to have a CI workflow, run against merges in the `main` branch, that does some basic tests against a live network, such as `PreviewNet`.

**Comment by sideninja** [comment]
I already have an e2e test suite I run locally against Previewnet, I was planning to add it to the codebase. That can then be used as part of the CI, but I wouldn't do that on each commit, I would only run it on a PR merged or a new release made, so we don't spam the network too much

**Comment by m-Peter** [comment]
Yep, I agree with that approach. I also mentioned this in the description:
> run against merges in the `main` branch
