### ISSUE TITLE
Use the proper value for `EffectiveGasPrice`

### ISSUE THREAD

**Issue by m-Peter** [onflow/flow-evm-gateway#355]
As described in https://docs.infura.io/api/networks/ethereum/json-rpc-methods/eth_gettransactionreceipt:
> effectiveGasPrice: The actual value per gas deducted from the sender's account. Before [EIP-1559](https://docs.infura.io/api/networks/ethereum/concepts/transaction-types#eip-1559-transactions), equal to the gas price.

Currently we use the gas price the sender is willing to pay (https://github.com/onflow/flow-evm-gateway/blob/main/models/receipt.go#L158), which is not necessarily the charged value. We need to be using the gas price that was **charged** for a given transaction.

Using the gas price that is set by the EVM Gateway operators, at the time the transaction was processed, is also not sufficient, as different EVM Gateway operators, will set different gas prices.

Most likely, this value has to be included in the payload of `EVM.TransactionExecuted` event.

**Comment by ramtinms** [comment]
Since we don't have any basefee on the network the effective gas price is always with this formula 
Min(GasTipCap, GasFeeCap)

**Comment by ramtinms** [comment]
on Tx object itself you can all EffectiveGasTip and pass nil to it.

**Comment by ramtinms** [comment]
hmm, I don't EVM Gateway operators can set any value, basically they can ignore transactions that has GasTipCap below their target. so anyway the effective gas used by transactions can be computed using the formula I mentioned.
