### ISSUE TITLE
Implement APIs to store and index blocks and provide block-related endpoints

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-evm-gateway#5]
This issue continues breaking down the formal [Ethereum RPC spec](https://ethereum.github.io/execution-apis/api-documentation/) into dependency ordered chunks. This issue groups a set of APIs which store and index blocks and provide block-related endpoints.

- eth_getBlockByHash
- eth_getBlockByNumber
- eth_getBlockReceipts
- eth_getBlockTransactionCountByHash
- eth_getBlockTransactionCountByNumber

We will need to:

Understand the internal wiring to be implemented and what interactions with BridgedAccount or other Flow constructs this will have in the functions implementation. Formalize the specification/requirements through discussion in this issue
Implement the endpoints above including corresponding automated tests to the agreed upon spec

**Comment by m-Peter** [comment]
I will open a follow-up PR for `eth_getBlockReceipts`.
