### ISSUE TITLE
Gas Limit reported lower than the Gas Used of a block

### ISSUE THREAD

**Issue by infsaulo** [onflow/flow-evm-gateway#558]
### Problem

For block  at height 755106, the `gasLimit` value is lower than the `gasUsed`. Wondering, based on EIP-1559 if the `gasLimit` should be bumped up to the max cap of 30M, as `gasUsed` target more than 15M of the limit.

### Steps to Reproduce 

```
curl https://mainnet.evm.nodes.onflow.org -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0xB85A2", false],"id":1}' | jq
``` 
  
### Context

Running a block parser and found under the validation step `gasLimit` < `gasUsed`

**Comment by m-Peter** [comment]
@infsaulo Nice catch :100: We need to update that constant for the block gas limit. And I guess it might go over 30M as well.
