### ISSUE TITLE
Binary version

### ISSUE THREAD

**Issue by Maharacha** [onflow/flow-evm-gateway#563]
Is it correct that checking the version of the binary is not supported? E.g. `evm-gateway --version`. Is that something that can be added?

**Comment by m-Peter** [comment]
Maybe the following endpoint can be useful:
```bash
curl -s -XPOST 'https://testnet.evm.nodes.onflow.org' --header 'Content-Type: application/json' --data-raw '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":7}' | jq
```
```json
{
  "jsonrpc": "2.0",
  "id": 7,
  "result": "flow-evm-gateway@v0.37.0-preview-5"
}
```
But that also is specific to how the binary is being built. See:
- https://github.com/onflow/flow-evm-gateway/blob/main/.github/workflows/build.yml#L39
- https://github.com/onflow/flow-evm-gateway/blob/main/Dockerfile#L18

**Comment by Maharacha** [comment]
I build the binary with `go build -o evm-gateway cmd/main/main.go` and then `web3_clientVersion` is only showing `flow-evm-gateway@development`. Will it be added as a cli option to the binary?

**Comment by Maharacha** [comment]
@m-Peter yes that works, and is better than nothing! But it would be nice to be able to check the binary version without having to start the node. It is useful for troubleshooting in an environment where you have nodes that have crashed for whatever reasons.

**Comment by m-Peter** [comment]
> @m-Peter yes that works, and is better than nothing! But it would be nice to be able to check the binary version without having to start the node. It is useful for troubleshooting in an environment where you have nodes that have crashed for whatever reasons.

@Maharacha That is a good point indeed :+1: We'll work on a solution to provide that functionality.

**Comment by Maharacha** [comment]
> > @m-Peter yes that works, and is better than nothing! But it would be nice to be able to check the binary version without having to start the node. It is useful for troubleshooting in an environment where you have nodes that have crashed for whatever reasons.
> 
> @Maharacha That is a good point indeed 👍 We'll work on a solution to provide that functionality.

Thanks! And thanks for the workaround in the meantime!

**Comment by Maharacha** [comment]
FYI. `flow-go` has the same problem but I just found out that I can at least get the version by running:
```
./flow-go --help 2>&1|grep version
{"level":"info","version":"v0.37.10","commit":"feabd3a4f9baaa5d7770a312e5b8dc1bd94b1edb","message":"build details"}
```

Another problem with both `flow-evm-gateway` and `flow-go` is that the output from `--help` is written to `stderr` and not `stdout` (hence the need for `2>&1`). Should be a separate issue of course, should I create one?
