### ISSUE TITLE
Deploy on a testnet with local AN and monitor metrics

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-evm-gateway#581]
We should deploy EVM GW node and AN node on the same machine so we make the network latency as low as possible. The AN should have complete history of indexed registers and allow event streaming. It should also not have rate-limits on the register APIs or those should be sufficiently high. If the rate-limits are not disabled we should validate the requests are successfully processed during stress-testing.

**Comment by j1010001** [comment]
no longer needed, moving to dry-run solution (https://github.com/onflow/flow-go/issues/6539)
