### ISSUE TITLE
Stress test the node with load of transactions

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-evm-gateway#582]
A deployment made to the testnet should have a client that requests re-execution of each transaction. That can be done by requesting traces, since trace production require re-execution of the state. 

This would make sure the transactions can be reproduced and after the #584 we can also make sure they were correctly re-executed. 

This will also provide us with good metrics we can use to judge scaling of the GW. 

We can have another stress-test that actually submits loads of transactions to the network, but keep in mind that will stress-test the whole network. 

Along with transaction re-execution requests by using traces, we should also do queries to the state (requests like getting balance, getting nonce, estimating gas etc).

**Comment by j1010001** [comment]
no longer needed, moving to dry-run solution (https://github.com/onflow/flow-go/issues/6539)
