### ISSUE TITLE
Validate and protect against register API index delays

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-evm-gateway#585]
There could be a case where the transaction re-execution request is made or a call is made and using the remote register APIs we fail to execute because the AN did not yet index that register. We should make sure such cases can't happen. Right now the EVM GW node is configured to allow querying all the sealed blocks heights. We must make sure that once the block height is sealed the registers will be indexed. 
If that is not the case we should guard and differentiate between register not existing and register not being indexed yet.

**Comment by j1010001** [comment]
no londer needed, moving to dry-run solution (https://github.com/onflow/flow-go/issues/6539)
