### ISSUE TITLE
Improve trace production

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-evm-gateway#588]
Right now trace production is being done on-demand so it can server different possible configurations of the tracers. 

We should work on producing most common traces up front and serving them from a local index instead of on-demand. That would significantly lower the load on the node producing the traces on-demand.

**Comment by j1010001** [comment]
No longer relevant, we are moving back to dry-run (https://github.com/onflow/flow-go/issues/6539) to implement better solution for providing traces.
