### ISSUE TITLE
eth_getLog() returns null instead of list if there are no transactions

### ISSUE THREAD

**Issue by j1010001** [onflow/flow-evm-gateway#695]
example:

`curl -XPOST 'https://testnet.evm.nodes.onflow.org' -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1318572,"method":"eth_getLogs","params":[{"blockHash":"0x4967b45f073cb74e750536d41fdb70ae3923d8a151abdbef25e4fd77d27fe253","address": ["0x0000000071727de22e5e9d8baf0edac6f37da032"],"topics": ["0x2da466a7b24304f47e87fa2e1e5a81b9831ce54fec19055ce277ca2f39ba42c4","0x49628fd1471006c1482da88028e9ce4dbb080b815c9b0344d39e5a8e6ec1419f","0xd1c19fbcd4551a5edfb66d43d2e337c04837afda3482b42bdf569a8fccdae5fb"]}]}' | jq`

return:
```
{
  "jsonrpc": "2.0",
  "id": 1318572,
  "result": null
}
```

### Problem

should return empty list instead of null

**Comment by m-Peter** [comment]
Completed by https://github.com/onflow/flow-evm-gateway/pull/697
