### ISSUE TITLE
Implement unsupported API methods 

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-evm-gateway#8]
This issue continues breaking down the formal [Ethereum RPC spec](https://ethereum.github.io/execution-apis/api-documentation/) into dependency ordered chunks. This issue is to implement unsupported API methods which return an not implemented error.

- eth_accounts
- eth_sign
- eth_signTransaction 
- eth_sendTransaction

We will need to:

Understand the internal wiring to be implemented and what interactions with BridgedAccount or other Flow constructs this will have in the functions implementation. Formalize the specification/requirements through discussion in this issue
Implement the endpoints above including corresponding automated tests to the agreed upon spec

**Comment by bthaile** [comment]
Prob already know, but here are all the methods.
https://docs.evmos.org/develop/api/ethereum-json-rpc/methods

Top 10 methods:
- `eth_blockNumber`: Returns the number of the most recent block.
- `eth_getBalance`: Returns the balance of the account at a given address.
- `eth_getTransactionCount`: Returns the number of transactions sent from an address.
- `eth_sendRawTransaction`: Submits a pre-signed transaction for broadcast to the Ethereum network.
- `eth_call`: Executes a new message call immediately without creating a transaction on the blockchain.
- `eth_getTransactionReceipt`: Returns the receipt of a transaction by transaction hash.
- `eth_gasPrice`: Returns the current price per gas in wei.
- `eth_estimateGas`: Makes an estimate of how much gas is necessary to allow a transaction to complete.
- `eth_getBlockByNumber`: Returns information about a block by block number.
- `eth_getTransactionByHash`: Returns the information about a transaction requested by transaction hash.

**Comment by sideninja** [comment]
Events are also commonly used, I would say most apps rely on them.
