### ISSUE TITLE
Web3 client acceptance testing

### ISSUE THREAD

**Issue by m-Peter** [onflow/flow-evm-gateway#82]
Implementing tests using a known client like web3.js will give us confidence the APIs are correctly implemented. This will act as an acceptance testing of the APIs. This is not supposed to cover edge cases and complex scenarios (we have e2e and unit tests for that) it should only cover a happy path.

We should test more of the JSON-RPC API endpoints through the `web3.js` library.
This will help in identifying issues related to input arguments and return values.

Improve existing `integration/web3` tests to be run with e2e tests. Also expand on what is being tested, use more methods. This will ensure the web3 clients can successfully communicate with the API and it's needed beside e2e tests because web3 clients sometimes rely on specific return values or schemas that we won't detect an issue with in e2e tests.

**Comment by gregsantos** [comment]
@bthaile  maybe we can hit some of these is a script and use as ref on client docs side
